main: com.gmail.markushygedombrowski.HLWarp
version: "1.0"
api-version: "1.21.8"
name: HLWarp
depend: []
commands:
  hlwarp:
    aliases: ["hlsetwarp", "hlwarpdelete", "hlwarplist"]
    description: "HLWarp System"
  hlwarpreload:
    description: "reload"